//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/error_code.proto
namespace WNet
{
    [global::ProtoBuf.ProtoContract(Name=@"enum_error_code")]
    public enum enum_error_code
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"success", Value=0)]
      success = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"not_enough_resource", Value=1)]
      not_enough_resource = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"not_enough_population", Value=2)]
      not_enough_population = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"no_active_guard", Value=10100)]
      no_active_guard = 10100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"guard_active", Value=10101)]
      guard_active = 10101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"guard_locked", Value=10102)]
      guard_locked = 10102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"guard_not_active", Value=10103)]
      guard_not_active = 10103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"has_no_troop", Value=10104)]
      has_no_troop = 10104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"not_in_produce", Value=10200)]
      not_in_produce = 10200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"produce_not_finished", Value=10201)]
      produce_not_finished = 10201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"object_not_found", Value=10300)]
      object_not_found = 10300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"alreay_in_attacking", Value=10350)]
      alreay_in_attacking = 10350,
            
      [global::ProtoBuf.ProtoEnum(Name=@"one_allowed_pos", Value=10351)]
      one_allowed_pos = 10351
    }
  
}