//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/up.proto
// Note: requires additional types generated from: common.proto
namespace WNet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"up_msg")]
  public partial class up_msg : global::ProtoBuf.IExtensible
  {
    public up_msg() {}
    
    private WNet.msg_heartbeat _heartbeat = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"heartbeat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_heartbeat heartbeat
    {
      get { return _heartbeat; }
      set { _heartbeat = value; }
    }
    private WNet.msg_login _login = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_login login
    {
      get { return _login; }
      set { _login = value; }
    }
    private WNet.msg_playerdata_request _playerdata_request = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerdata_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_playerdata_request playerdata_request
    {
      get { return _playerdata_request; }
      set { _playerdata_request = value; }
    }
    private WNet.msg_mapdata_request _mapdata_request = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mapdata_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_mapdata_request mapdata_request
    {
      get { return _mapdata_request; }
      set { _mapdata_request = value; }
    }
    private WNet.msg_add_mapobject_request _add_mapobject_request = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"add_mapobject_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_add_mapobject_request add_mapobject_request
    {
      get { return _add_mapobject_request; }
      set { _add_mapobject_request = value; }
    }
    private WNet.msg_move_request _move_request = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"move_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_move_request move_request
    {
      get { return _move_request; }
      set { _move_request = value; }
    }
    private WNet.msg_stopmove_request _stopmove_request = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"stopmove_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_stopmove_request stopmove_request
    {
      get { return _stopmove_request; }
      set { _stopmove_request = value; }
    }
    private WNet.msg_attack_request _attack_request = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"attack_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_attack_request attack_request
    {
      get { return _attack_request; }
      set { _attack_request = value; }
    }
    private WNet.msg_resdata_request _resdata_request = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"resdata_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_resdata_request resdata_request
    {
      get { return _resdata_request; }
      set { _resdata_request = value; }
    }
    private WNet.msg_collect_res_request _collect_res_request = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"collect_res_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_collect_res_request collect_res_request
    {
      get { return _collect_res_request; }
      set { _collect_res_request = value; }
    }
    private WNet.msg_tech_request _tech_request = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"tech_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_tech_request tech_request
    {
      get { return _tech_request; }
      set { _tech_request = value; }
    }
    private WNet.msg_ranking_request _ranking_request = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"ranking_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_ranking_request ranking_request
    {
      get { return _ranking_request; }
      set { _ranking_request = value; }
    }
    private WNet.msg_task_request _task_request = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"task_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_task_request task_request
    {
      get { return _task_request; }
      set { _task_request = value; }
    }
    private WNet.msg_task_get_award_request _task_get_award_request = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"task_get_award_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_task_get_award_request task_get_award_request
    {
      get { return _task_get_award_request; }
      set { _task_get_award_request = value; }
    }
    private WNet.msg_army_combine_request _army_combine_request = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"army_combine_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_army_combine_request army_combine_request
    {
      get { return _army_combine_request; }
      set { _army_combine_request = value; }
    }
    private WNet.msg_change_army_id_request _change_army_id_request = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"change_army_id_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_change_army_id_request change_army_id_request
    {
      get { return _change_army_id_request; }
      set { _change_army_id_request = value; }
    }
    private WNet.msg_building_create_request _building_create_request = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"building_create_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_building_create_request building_create_request
    {
      get { return _building_create_request; }
      set { _building_create_request = value; }
    }
    private WNet.msg_building_init_request _building_init_request = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"building_init_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_building_init_request building_init_request
    {
      get { return _building_init_request; }
      set { _building_init_request = value; }
    }
    private WNet.msg_recycle_army_request _recycle_army_request = null;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"recycle_army_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_recycle_army_request recycle_army_request
    {
      get { return _recycle_army_request; }
      set { _recycle_army_request = value; }
    }
    private WNet.msg_recycle_building_request _recycle_building_request = null;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"recycle_building_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_recycle_building_request recycle_building_request
    {
      get { return _recycle_building_request; }
      set { _recycle_building_request = value; }
    }
    private WNet.msg_movebase_request _movebase_request = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"movebase_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_movebase_request movebase_request
    {
      get { return _movebase_request; }
      set { _movebase_request = value; }
    }
    private WNet.msg_base_state_init _base_state_init_request = null;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"base_state_init_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_base_state_init base_state_init_request
    {
      get { return _base_state_init_request; }
      set { _base_state_init_request = value; }
    }
    private WNet.msg_change_map_request _change_map_request = null;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"change_map_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_change_map_request change_map_request
    {
      get { return _change_map_request; }
      set { _change_map_request = value; }
    }
    private WNet.msg_set_player_uint_data _set_player_uint_data = null;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"set_player_uint_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_set_player_uint_data set_player_uint_data
    {
      get { return _set_player_uint_data; }
      set { _set_player_uint_data = value; }
    }
    private WNet.msg_recruit_req _recruit_req = null;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"recruit_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_recruit_req recruit_req
    {
      get { return _recruit_req; }
      set { _recruit_req = value; }
    }
    private WNet.msg_dungeon_req _dungeon_req = null;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"dungeon_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_dungeon_req dungeon_req
    {
      get { return _dungeon_req; }
      set { _dungeon_req = value; }
    }
    private WNet.msg_mine_req _mine_req = null;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"mine_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_mine_req mine_req
    {
      get { return _mine_req; }
      set { _mine_req = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_login")]
  public partial class msg_login : global::ProtoBuf.IExtensible
  {
    public msg_login() {}
    
    private string _open_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"open_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string open_id
    {
      get { return _open_id; }
      set { _open_id = value; }
    }
    private WNet.plat_type _plat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"plat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public WNet.plat_type plat
    {
      get { return _plat; }
      set { _plat = value; }
    }
    private string _passwd;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passwd
    {
      get { return _passwd; }
      set { _passwd = value; }
    }
    private bool _need_pass;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"need_pass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool need_pass
    {
      get { return _need_pass; }
      set { _need_pass = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_playerdata_request")]
  public partial class msg_playerdata_request : global::ProtoBuf.IExtensible
  {
    public msg_playerdata_request() {}
    
    private uint _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_mapdata_request")]
  public partial class msg_mapdata_request : global::ProtoBuf.IExtensible
  {
    public msg_mapdata_request() {}
    
    private uint _map_inst_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"map_inst_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint map_inst_id
    {
      get { return _map_inst_id; }
      set { _map_inst_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_resdata_request")]
  public partial class msg_resdata_request : global::ProtoBuf.IExtensible
  {
    public msg_resdata_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_heartbeat")]
  public partial class msg_heartbeat : global::ProtoBuf.IExtensible
  {
    public msg_heartbeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_add_mapobject_request")]
  public partial class msg_add_mapobject_request : global::ProtoBuf.IExtensible
  {
    public msg_add_mapobject_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }
    private uint _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private uint _object_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"object_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint object_type
    {
      get { return _object_type; }
      set { _object_type = value; }
    }
    private uint _camp_type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"camp_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint camp_type
    {
      get { return _camp_type; }
      set { _camp_type = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _type_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"type_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> type_id
    {
      get { return _type_id; }
    }
  
    private uint _army_id = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"army_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint army_id
    {
      get { return _army_id; }
      set { _army_id = value; }
    }
    private uint _master_army_id = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"master_army_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint master_army_id
    {
      get { return _master_army_id; }
      set { _master_army_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_move_request")]
  public partial class msg_move_request : global::ProtoBuf.IExtensible
  {
    public msg_move_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private uint _current_x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"current_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint current_x
    {
      get { return _current_x; }
      set { _current_x = value; }
    }
    private uint _current_y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"current_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint current_y
    {
      get { return _current_y; }
      set { _current_y = value; }
    }
    private uint _target_x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"target_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint target_x
    {
      get { return _target_x; }
      set { _target_x = value; }
    }
    private uint _target_y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"target_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint target_y
    {
      get { return _target_y; }
      set { _target_y = value; }
    }
    private float _start_pos_x;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"start_pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float start_pos_x
    {
      get { return _start_pos_x; }
      set { _start_pos_x = value; }
    }
    private float _start_pos_y;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"start_pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float start_pos_y
    {
      get { return _start_pos_y; }
      set { _start_pos_y = value; }
    }
    private float _start_pos_z;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"start_pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float start_pos_z
    {
      get { return _start_pos_z; }
      set { _start_pos_z = value; }
    }
    private float _move_duration;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"move_duration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float move_duration
    {
      get { return _move_duration; }
      set { _move_duration = value; }
    }
    private uint _is_start;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"is_start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint is_start
    {
      get { return _is_start; }
      set { _is_start = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _path_ids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"path_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> path_ids
    {
      get { return _path_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_stopmove_request")]
  public partial class msg_stopmove_request : global::ProtoBuf.IExtensible
  {
    public msg_stopmove_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private uint _current_x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"current_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint current_x
    {
      get { return _current_x; }
      set { _current_x = value; }
    }
    private uint _current_y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"current_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint current_y
    {
      get { return _current_y; }
      set { _current_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_damage_data_request")]
  public partial class msg_damage_data_request : global::ProtoBuf.IExtensible
  {
    public msg_damage_data_request() {}
    
    private uint _target_owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target_owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint target_owner_id
    {
      get { return _target_owner_id; }
      set { _target_owner_id = value; }
    }
    private uint _target_unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target_unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint target_unique_id
    {
      get { return _target_unique_id; }
      set { _target_unique_id = value; }
    }
    private uint _damage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_attack_request")]
  public partial class msg_attack_request : global::ProtoBuf.IExtensible
  {
    public msg_attack_request() {}
    
    private uint _attacker_owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"attacker_owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint attacker_owner_id
    {
      get { return _attacker_owner_id; }
      set { _attacker_owner_id = value; }
    }
    private uint _attacker_unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attacker_unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint attacker_unique_id
    {
      get { return _attacker_unique_id; }
      set { _attacker_unique_id = value; }
    }
    private WNet.msg_damage_data_request _damage_datas;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"damage_datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public WNet.msg_damage_data_request damage_datas
    {
      get { return _damage_datas; }
      set { _damage_datas = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_morale_recover_request")]
  public partial class msg_morale_recover_request : global::ProtoBuf.IExtensible
  {
    public msg_morale_recover_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private int _cur_morale;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cur_morale", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cur_morale
    {
      get { return _cur_morale; }
      set { _cur_morale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_lowmorale_state_request")]
  public partial class msg_lowmorale_state_request : global::ProtoBuf.IExtensible
  {
    public msg_lowmorale_state_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_collect_res_request")]
  public partial class msg_collect_res_request : global::ProtoBuf.IExtensible
  {
    public msg_collect_res_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private uint _map_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"map_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint map_id
    {
      get { return _map_id; }
      set { _map_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_tech_request")]
  public partial class msg_tech_request : global::ProtoBuf.IExtensible
  {
    public msg_tech_request() {}
    
    private WNet.msg_all_tech_request _all_tech_request = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"all_tech_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_all_tech_request all_tech_request
    {
      get { return _all_tech_request; }
      set { _all_tech_request = value; }
    }
    private WNet.msg_tech_lv_up_request _tech_lv_up_request = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tech_lv_up_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_tech_lv_up_request tech_lv_up_request
    {
      get { return _tech_lv_up_request; }
      set { _tech_lv_up_request = value; }
    }
    private WNet.msg_tech_receive_request _tech_receive_request = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tech_receive_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_tech_receive_request tech_receive_request
    {
      get { return _tech_receive_request; }
      set { _tech_receive_request = value; }
    }
    private WNet.msg_tech_resume_request _tech_resume_request = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tech_resume_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_tech_resume_request tech_resume_request
    {
      get { return _tech_resume_request; }
      set { _tech_resume_request = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_all_tech_request")]
  public partial class msg_all_tech_request : global::ProtoBuf.IExtensible
  {
    public msg_all_tech_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_tech_resume_request")]
  public partial class msg_tech_resume_request : global::ProtoBuf.IExtensible
  {
    public msg_tech_resume_request() {}
    
    private uint _tech_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tech_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tech_id
    {
      get { return _tech_id; }
      set { _tech_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_tech_lv_up_request")]
  public partial class msg_tech_lv_up_request : global::ProtoBuf.IExtensible
  {
    public msg_tech_lv_up_request() {}
    
    private uint _tech_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tech_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tech_id
    {
      get { return _tech_id; }
      set { _tech_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_tech_receive_request")]
  public partial class msg_tech_receive_request : global::ProtoBuf.IExtensible
  {
    public msg_tech_receive_request() {}
    
    private uint _tech_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tech_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tech_id
    {
      get { return _tech_id; }
      set { _tech_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_revive_request")]
  public partial class msg_revive_request : global::ProtoBuf.IExtensible
  {
    public msg_revive_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_ranking_request")]
  public partial class msg_ranking_request : global::ProtoBuf.IExtensible
  {
    public msg_ranking_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_task_request")]
  public partial class msg_task_request : global::ProtoBuf.IExtensible
  {
    public msg_task_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_task_get_award_request")]
  public partial class msg_task_get_award_request : global::ProtoBuf.IExtensible
  {
    public msg_task_get_award_request() {}
    
    private uint _task_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint task_id
    {
      get { return _task_id; }
      set { _task_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_army_combine_request")]
  public partial class msg_army_combine_request : global::ProtoBuf.IExtensible
  {
    public msg_army_combine_request() {}
    
    private uint _servant_owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"servant_owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint servant_owner_id
    {
      get { return _servant_owner_id; }
      set { _servant_owner_id = value; }
    }
    private uint _servant_unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"servant_unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint servant_unique_id
    {
      get { return _servant_unique_id; }
      set { _servant_unique_id = value; }
    }
    private uint _master_owner_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"master_owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint master_owner_id
    {
      get { return _master_owner_id; }
      set { _master_owner_id = value; }
    }
    private uint _master_unique_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"master_unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint master_unique_id
    {
      get { return _master_unique_id; }
      set { _master_unique_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_change_army_id_request")]
  public partial class msg_change_army_id_request : global::ProtoBuf.IExtensible
  {
    public msg_change_army_id_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private uint _new_army_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"new_army_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint new_army_id
    {
      get { return _new_army_id; }
      set { _new_army_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_building_create_request")]
  public partial class msg_building_create_request : global::ProtoBuf.IExtensible
  {
    public msg_building_create_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _type_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type_id
    {
      get { return _type_id; }
      set { _type_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_building_init_request")]
  public partial class msg_building_init_request : global::ProtoBuf.IExtensible
  {
    public msg_building_init_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_recycle_army_update_req_data")]
  public partial class msg_recycle_army_update_req_data : global::ProtoBuf.IExtensible
  {
    public msg_recycle_army_update_req_data() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _type_ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"type_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> type_ids
    {
      get { return _type_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_recycle_army_remove_req_data")]
  public partial class msg_recycle_army_remove_req_data : global::ProtoBuf.IExtensible
  {
    public msg_recycle_army_remove_req_data() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_recycle_army_request")]
  public partial class msg_recycle_army_request : global::ProtoBuf.IExtensible
  {
    public msg_recycle_army_request() {}
    
    private readonly global::System.Collections.Generic.List<WNet.msg_recycle_army_update_req_data> _recycle_army_update_req_data = new global::System.Collections.Generic.List<WNet.msg_recycle_army_update_req_data>();
    [global::ProtoBuf.ProtoMember(1, Name=@"recycle_army_update_req_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WNet.msg_recycle_army_update_req_data> recycle_army_update_req_data
    {
      get { return _recycle_army_update_req_data; }
    }
  
    private readonly global::System.Collections.Generic.List<WNet.msg_recycle_army_remove_req_data> _recycle_army_remove_req_data = new global::System.Collections.Generic.List<WNet.msg_recycle_army_remove_req_data>();
    [global::ProtoBuf.ProtoMember(2, Name=@"recycle_army_remove_req_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WNet.msg_recycle_army_remove_req_data> recycle_army_remove_req_data
    {
      get { return _recycle_army_remove_req_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_recycle_building_request")]
  public partial class msg_recycle_building_request : global::ProtoBuf.IExtensible
  {
    public msg_recycle_building_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_movebase_request")]
  public partial class msg_movebase_request : global::ProtoBuf.IExtensible
  {
    public msg_movebase_request() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }
    private uint _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_base_state_init")]
  public partial class msg_base_state_init : global::ProtoBuf.IExtensible
  {
    public msg_base_state_init() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_change_map_request")]
  public partial class msg_change_map_request : global::ProtoBuf.IExtensible
  {
    public msg_change_map_request() {}
    
    private uint _map_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"map_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint map_id
    {
      get { return _map_id; }
      set { _map_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_set_player_uint_data")]
  public partial class msg_set_player_uint_data : global::ProtoBuf.IExtensible
  {
    public msg_set_player_uint_data() {}
    
    private uint _owner_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private WNet.player_uint_data_type _data_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public WNet.player_uint_data_type data_type
    {
      get { return _data_type; }
      set { _data_type = value; }
    }
    private uint _data_value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"data_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint data_value
    {
      get { return _data_value; }
      set { _data_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_recruit_req")]
  public partial class msg_recruit_req : global::ProtoBuf.IExtensible
  {
    public msg_recruit_req() {}
    
    private WNet.msg_recruit_add_request _recruit_add_request = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"recruit_add_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_recruit_add_request recruit_add_request
    {
      get { return _recruit_add_request; }
      set { _recruit_add_request = value; }
    }
    private WNet.msg_recruit_cancel_request _recruit_cancel_request = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"recruit_cancel_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_recruit_cancel_request recruit_cancel_request
    {
      get { return _recruit_cancel_request; }
      set { _recruit_cancel_request = value; }
    }
    private WNet.msg_recruit_receive_request _recruit_receive_request = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"recruit_receive_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_recruit_receive_request recruit_receive_request
    {
      get { return _recruit_receive_request; }
      set { _recruit_receive_request = value; }
    }
    private WNet.set_troop_template_req _set_troop_template_req = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"set_troop_template_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.set_troop_template_req set_troop_template_req
    {
      get { return _set_troop_template_req; }
      set { _set_troop_template_req = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_recruit_add_request")]
  public partial class msg_recruit_add_request : global::ProtoBuf.IExtensible
  {
    public msg_recruit_add_request() {}
    
    private readonly global::System.Collections.Generic.List<WNet.uint32_kv> _recruit_list = new global::System.Collections.Generic.List<WNet.uint32_kv>();
    [global::ProtoBuf.ProtoMember(1, Name=@"recruit_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WNet.uint32_kv> recruit_list
    {
      get { return _recruit_list; }
    }
  
    private WNet.recruit_type _type = WNet.recruit_type.recruit_nornal;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(WNet.recruit_type.recruit_nornal)]
    public WNet.recruit_type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_recruit_cancel_request")]
  public partial class msg_recruit_cancel_request : global::ProtoBuf.IExtensible
  {
    public msg_recruit_cancel_request() {}
    
    private WNet.uint32_kv _cancel_unit;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cancel_unit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public WNet.uint32_kv cancel_unit
    {
      get { return _cancel_unit; }
      set { _cancel_unit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_recruit_receive_request")]
  public partial class msg_recruit_receive_request : global::ProtoBuf.IExtensible
  {
    public msg_recruit_receive_request() {}
    
    private readonly global::System.Collections.Generic.List<WNet.uint32_kv> _recruit_receive_list = new global::System.Collections.Generic.List<WNet.uint32_kv>();
    [global::ProtoBuf.ProtoMember(1, Name=@"recruit_receive_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WNet.uint32_kv> recruit_receive_list
    {
      get { return _recruit_receive_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"set_troop_template_req")]
  public partial class set_troop_template_req : global::ProtoBuf.IExtensible
  {
    public set_troop_template_req() {}
    
    private WNet.uint32_kvl _template;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"template", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public WNet.uint32_kvl template
    {
      get { return _template; }
      set { _template = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_dungeon_req")]
  public partial class msg_dungeon_req : global::ProtoBuf.IExtensible
  {
    public msg_dungeon_req() {}
    
    private WNet.msg_enter_guard _enter_guard = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"enter_guard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_enter_guard enter_guard
    {
      get { return _enter_guard; }
      set { _enter_guard = value; }
    }
    private WNet.msg_exit_guard _exit_guard = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exit_guard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_exit_guard exit_guard
    {
      get { return _exit_guard; }
      set { _exit_guard = value; }
    }
    private WNet.msg_get_guard_mapdata _get_guard_mapdata = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"get_guard_mapdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_get_guard_mapdata get_guard_mapdata
    {
      get { return _get_guard_mapdata; }
      set { _get_guard_mapdata = value; }
    }
    private WNet.msg_get_battle_reward _get_battle_reward = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"get_battle_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_get_battle_reward get_battle_reward
    {
      get { return _get_battle_reward; }
      set { _get_battle_reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_enter_guard")]
  public partial class msg_enter_guard : global::ProtoBuf.IExtensible
  {
    public msg_enter_guard() {}
    
    private uint _dungeon_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dungeon_id
    {
      get { return _dungeon_id; }
      set { _dungeon_id = value; }
    }
    private uint _guard_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guard_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint guard_id
    {
      get { return _guard_id; }
      set { _guard_id = value; }
    }
    private bool _restart = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"restart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool restart
    {
      get { return _restart; }
      set { _restart = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_exit_guard")]
  public partial class msg_exit_guard : global::ProtoBuf.IExtensible
  {
    public msg_exit_guard() {}
    
    private uint _dungeon_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dungeon_id
    {
      get { return _dungeon_id; }
      set { _dungeon_id = value; }
    }
    private uint _guard_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guard_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint guard_id
    {
      get { return _guard_id; }
      set { _guard_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_get_guard_mapdata")]
  public partial class msg_get_guard_mapdata : global::ProtoBuf.IExtensible
  {
    public msg_get_guard_mapdata() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_get_battle_reward")]
  public partial class msg_get_battle_reward : global::ProtoBuf.IExtensible
  {
    public msg_get_battle_reward() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_mine_req")]
  public partial class msg_mine_req : global::ProtoBuf.IExtensible
  {
    public msg_mine_req() {}
    
    private WNet.msg_take_resource_req _take_resource_req = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"take_resource_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WNet.msg_take_resource_req take_resource_req
    {
      get { return _take_resource_req; }
      set { _take_resource_req = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_take_resource_req")]
  public partial class msg_take_resource_req : global::ProtoBuf.IExtensible
  {
    public msg_take_resource_req() {}
    
    private uint _map_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"map_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint map_id
    {
      get { return _map_id; }
      set { _map_id = value; }
    }
    private uint _unique_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unique_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unique_id
    {
      get { return _unique_id; }
      set { _unique_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}